# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    paths:
      - ".github/workflows/azure-functions-app-dotnet.yml"
      - "Plugins/Unzer.Plugin.Payments.Unzer/**"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        directory: /home/runner/work/nopCommerce-4.80-Plugins/nopCommerce-4.80-Plugins/Presentation/Nop.Web/Plugins/Payments.Unzer/
        filename: 'nop4.80-Payments.Unzer-V1.zip'
    - uses: softprops/action-gh-release@v2
      with:
       files: |
         /home/runner/work/nopCommerce-4.80-Plugins/nopCommerce-4.80-Plugins/Presentation/Nop.Web/Plugins/Payments.Unzer/nop4.80-Payments.Unzer-V1.zip
       body: "nopCommerce Plugin Unzer Payment"
       tag_name: ${{ github.ref_name }}      
